import type { Metadata } from 'next'
 
// These styles apply to every route in the application
import './globals.css'
import StoreProvider from './StoreProvider'

export const metadata: Metadata = {
  title: 'Generathon',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body>
          <StoreProvider>
            {children}
          </StoreProvider>
        </body>
    </html>
  )
}